# Practical 09

**Aim:** Demonstrate the data science life cycle and perform Univariate, Bivariate and Multivariate analysis on a real-world dataset.

In [1]:
import pandas as pd

df = pd.read_csv("employee.csv")

### 1. Univariate

In [2]:
df["DistanceFromHome"].describe()

count    1470.000000
mean        9.192517
std         8.106864
min         1.000000
25%         2.000000
50%         7.000000
75%        14.000000
max        29.000000
Name: DistanceFromHome, dtype: float64

### 2. Bivariate

In [ ]:
df[["Education", "JobLevel"]].describe()

         Education     JobLevel
count  1470.000000  1470.000000
mean      2.912925     2.063946
std       1.024165     1.106940
min       1.000000     1.000000
25%       2.000000     1.000000
50%       3.000000     2.000000
75%       4.000000     3.000000
max       5.000000     5.000000

### 3. Multivariate

In [4]:
df[["NumCompaniesWorked", "YearsSinceLastPromotion", "StockOptionLevel"]].describe()

       NumCompaniesWorked  YearsSinceLastPromotion  StockOptionLevel
count         1470.000000              1470.000000       1470.000000
mean             2.693197                 2.187755          0.793878
std              2.498009                 3.222430          0.852077
min              0.000000                 0.000000          0.000000
25%              1.000000                 0.000000          0.000000
50%              2.000000                 1.000000          1.000000
75%              4.000000                 3.000000          1.000000
max              9.000000                15.000000          3.000000